language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
script:
- "./build.sh"
deploy:
  provider: heroku
  api_key:
    secure: 3D+NEAh2DH5ci6zVEOeV99n1SAKnKSWvY9PO64+QE4XzF27rWP51/SAsPm/apHUWGQkm/Vf5nBENGDyJIQ3z5EFhYKxi4MU1yLWXsVOWsh5zal25BL2hWY+Aehf8yI+L4B+4Z5haAvhM74fL7vcZjYvxwY2X42aLqo9YOgfqU2iuYf7l2/IC0AVSnBnidP79zyODFBTf0O29zo1EhacaQos16YrisjcJWUAwXVpQnAzSO3eACW47s/Up3ousRwgTES2dauOGYAo5nYReFKID9N0tYN4sx95FU8LnsQ9e7grfj23k1zh17z/CAABeYeOOISdDC+ZERb2z8nLF62Cw7BrhY62gUIaVvk8tRDdm0oJaY6Ec9T/RPYsvi6yxu4K5QxvxfGwn5snBBU1eddtyH5JV8VogLQWhBneFc994wn5fv4V+Xm9O/mUfeki53FEIfgwB3dZF365R8SDA5PSTJO+7j+t5DZhGFqNAJTJnCs1GzvUxxbiUvI2zHS52JGrxMObTvBTzyQLZZASAkjcKs2cCxcax3j2R/sP79ryglbb2r7w09lI8OJQib8qZTabueJAJGVafH39ze6IP5oXDjOrFF1EZjozJgvPR3QW2ZxHmYOqCX0St4jQ9gD/Ugly2STXoy/sVCl34Vr2iglZn7kfiHvHyVPrxR2N+iyE82Yc=
