language: csharp
mono: none
dotnet: 3.1
install:
- dotnet tool restore
script:
- dotnet cake
deploy:
  provider: heroku
  api_key:
    secure: qHHoEwyetOsRgavTxG+9/j5yAHccbOftPILg/YUDhX1KxL/a6n2/yFMM3MHKKiT0IgDpZ50sS2kaGh6oqEVWyWhN0+Eh6XsGQ2oEyA/W1ve2rGgzgId7kvIrb0oP5hL1lRWRF55Lripst/qcB4qZp9tsiz/S5WMPxBmA4wtmNnPBjd7O27KT9FjIp/6BiPFEub8MwuobwKJvhkuIQCgfvUPlu+RRqHK95rD+NyMm3GOmcpGhdsFiWcqa93xgnVy/01OqD4B9kp9BjfrJLOtGt0LQHEJko728RD01dyzfEPAtqzQH/0Osh4G8RVIDgzxrIi28usGoaJklf/YKFOuzrlFrsFJTX5XAEL4LaXH2ivUCvMkU2yboKNkGDDqAhJKw0A5J89UIHb+2LJilV6I971zQ/A5jtMWdvXhUaile8Q/QXvliOM7hzDYHrUzDFF6MX4FQtH81pMXe8aXQnnp0pUp0kXdVJL171bCf0XEwLOZrWVrPSusUIGxe1Nxt7o0g36XCUbL54e00Gwkf+UQb/K2S7KxrYe4bn5Se59ER736J1vvbj4Z407zBTOa8PWKt8ToZouejQ7KQ53nxCaBQrRyigk+y0CKzrk219wyQIfSApFASAKh2bbUmEQ46RiSUUjMtBeGrQyvg8pPykkZFXbrycRvZb4BnrbdbbgAREAU=
